[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  call deoplete#enable()
'''

[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['c', 'cpp']
hook_source = '''
  let g:deoplete#sources#clang#libclang_path='/Applications/Xcode.app/Contents/Frameworks/libclang.dylib'
  let g:deoplete#sources#clang#clang_header='/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/Resources/'
  let g:deoplete#sources#clang#flags = ['-x', 'c++', '-std=c++11']
'''

[[plugins]]
repo = 'fishbullet/deoplete-ruby'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_post_source = '''
  call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
  call denite#custom#var('grep', 'command', ['ag'])
  call denite#custom#var('grep', 'recursive_opts', [])
  call denite#custom#var('grep', 'default_opts', ['--follow', '--no-group', '--no-color'])
'''

# Do 'go get -u github.com/nsf/gocode'
[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = ['go']
