[[plugins]]
repo = 'Shougo/deoplete.nvim'
let g:deoplete#enable_at_startup = 1

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_post_source = '''
call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
call denite#custom#var('grep', 'command', ['ag'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'default_opts', ['--follow', '--no-group', '--no-color'])
'''
